<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Moving_box">

<xacro:macro name="box_world" params="name">

		<xacro:property name="box_height" value="0.165"/>
		<xacro:property name="box_width" value="0.21"/>
		<xacro:property name="box_length" value="0.255"/>


		<link name="${name}">
			<visual>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
				<geometry>
					<box size="${box_length} ${box_width} ${box_height}"/>
				</geometry>

				<material name="Almond">
					<color rgba="0.7 0.5 0.3 1.0"/>
				</material>

			</visual>

			<collision>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
				<geometry>
					<box size="${box_length} ${box_width} ${box_height}"/>
				</geometry>

			</collision>

			<inertial>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
        <mass value="1.3729096e+00"/>
        <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04"
                iyy="8.6195418e-03" iyz="-3.5422299e-06"
                izz="1.4612727e-02" />

			</inertial>
		</link>


	</xacro:macro>
</robot>
