<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Moving_box">

<xacro:macro name="box_world" params="name">

		<xacro:property name="box_height" value="0.165"/>
		<xacro:property name="box_width" value="0.21"/>
		<xacro:property name="box_length" value="0.255"/>

    <link name = "base_link">
      <origin xyz="-0.215 -0.1275 0" rpy="0 0 1.57"/>
    </link>
		<joint name="${name}_joint" type="fixed">
      <origin xyz="-0.215 -0.1275 0" rpy="0 0 1.57"/>
			<parent link="base_link"/>
			<child link="${name}"/>
		</joint>

		<link name="${name}">
			<visual>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
				<geometry>
					<box size="${box_length} ${box_width} ${box_height}"/>
				</geometry>

				<material name="Almond">
					<color rgba="0.7 0.5 0.3 1.0"/>
				</material>

			</visual>

			<collision>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
				<geometry>
					<box size="${box_length} ${box_width} ${box_height}"/>
				</geometry>

			</collision>

			<inertial>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<mass value="0.18"/>
				<inertia ixx="6.0e-4" ixy="0" ixz="0" iyy="6.0e-4" iyz="0" izz="6.0e-4"/>

			</inertial>
		</link>


	</xacro:macro>
</robot>
