<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Moving_box">

	<xacro:macro name="box_world" params="name parent *origin">

		<xacro:property name="box_height" value="0.165"/>
		<xacro:property name="box_width" value="0.21"/>
		<xacro:property name="box_length" value="0.255"/>

		<link name="${name}">

			<visual>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<geometry>
					<box size="${box_length} ${box_width} ${box_height}"/>
				</geometry>

				<material name="Almond">
					<color rgba="0.7 0.5 0.3 1.0"/>
				</material>

			</visual>

			<collision>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<geometry>
					<box size="${box_length} ${box_width} ${box_height}"/>
				</geometry>

			</collision>

			<inertial>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<mass value="0.01"/>
				<inertia ixx="6.0e-4" ixy="0" ixz="0" iyy="6.0e-4" iyz="0" izz="6.0e-4"/>

			</inertial>

		</link>

		<joint name="${name}_joint" type="planar">

            <axis xyz= "0 0 1"/>
			<xacro:insert_block name="origin" />
			<parent link="${parent}"/>
			<child link="${name}"/>
		</joint>

	</xacro:macro>





</robot>
