<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Moving_box">

<xacro:macro name="box_world" params="name">

		<xacro:property name="box_height" value="0.165"/>
		<xacro:property name="box_width" value="0.21"/>
		<xacro:property name="box_length" value="0.255"/>


		<link name="${name}">
			<visual>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
				<geometry>
					<box size="${box_length} ${box_width} ${box_height}"/>
				</geometry>

				<material name="Almond">
					<color rgba="0.7 0.5 0.3 1.0"/>
				</material>

			</visual>

			<collision>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
				<geometry>
					<box size="${box_length} ${box_width} ${box_height}"/>
				</geometry>

			</collision>


			<inertial>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<mass value="0.180"/>
				<inertia ixx="2.0" ixy="0" ixz="0" iyy="2.0" iyz="0" izz="2.0"/>

			</inertial>


		</link>


	</xacro:macro>
</robot>
