<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="moving_box">

	<xacro:macro name="box_world" params="name">

		<xacro:property name="box_height" value="0.165"/>
		<xacro:property name="box_width" value="0.21"/>
		<xacro:property name="box_length" value="0.255"/>

		<link name="moving_box_base"/>

		<link name="${name}">

			<visual>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<geometry>
					<box size="${box_length} ${box_width} ${box_height}"/>
				</geometry>

				<material name="Almond">
					<color rgba="0.7 0.5 0.3 1.0"/>
				</material>

			</visual>

			<collision>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<geometry>
					<box size="${box_length}+0.01 ${box_width}+0.01 ${box_height}+0.01"/>
				</geometry>

			</collision>

			<inertial>

				<origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
				<mass value="0.180"/>
				<inertia ixx="0.166" ixy="0" ixz="0" iyy="0.166" iyz="0" izz="0.166"/>

			</inertial>

		</link>

		<joint name="${name}_joint" type="fixed">

			<origin xyz="-0.25 -0.265 0" rpy="0 0 1.57"/>
			<parent link="moving_box_base"/>
			<child link="${name}"/>
		
		</joint>


		<gazebo reference="${name}">
    	   <surface>
      		<friction>
        		<ode>
          			<mu>1</mu>
          			<mu2>1</mu2>
          			<slip1>0</slip1>
          			<slip2>0</slip2>
          			<fdir1>1 0 0 </fdir1>
        		</ode>
      		</friction>
      		<contact>
        		<ode>
          			<soft_cfm>0</soft_cfm>
          			<soft_erp>0.2</soft_erp>
          			<kp>1e+13</kp>
          			<kd>1</kd>
          			<max_vel>0.01</max_vel>
          			<min_depth>0</min_depth>
        		</ode>
      		</contact>
    		</surface>
    	</gazebo>

	</xacro:macro>

</robot>
